services:
  # dump:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dump
  #   environment:
  #     - CEDRO_USERNAME=${CEDRO_USERNAME}
  #     - CEDRO_PASSWORD=${CEDRO_PASSWORD}
  #     - CEDRO_TOKEN=${CEDRO_TOKEN}

  #   stdin_open: true
  #   tty: true

  #   volumes:
  #     - ./dumps:/app/dumps
    
  websocket-server-1:
    build:
      context: .
      dockerfile: Dockerfile.websocket-server
    stdin_open: true
    tty: true
    ports:
      - "3001:3000"
  websocket-server-2:
    build:
      context: .
      dockerfile: Dockerfile.websocket-server
    stdin_open: true
    tty: true
    ports:
      - "3002:3000"
  websocket-server-3:
    build:
      context: .
      dockerfile: Dockerfile.websocket-server
    stdin_open: true
    tty: true
    ports:
      - "3003:3000"
  websocket-server-4:
    build:
      context: .
      dockerfile: Dockerfile.websocket-server
    stdin_open: true
    tty: true
    ports:
      - "3004:3000"
  nginx:
    image: nginx:alpine
    ports:
      - "3000:3000"
    depends_on:
      - websocket-server-1
      - websocket-server-2
      - websocket-server-3
      - websocket-server-4
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro