# https://github.com/bitnami/containers/tree/main/bitnami/rabbitmq#how-to-use-this-image
# docker exec -it 3ee6d55c13ac bash
# http://localhost:15672/

version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ messaging port
      - "15672:15672" # Web UI port
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword
